### ISSUE TITLE
Blocking vs non-blocking ordering

### ISSUE THREAD

**Issue by pmeenan** [kazuho/draft-kazuho-httpbis-priority#13] opened 2019-07-03 21:42 UTC
One fairly common pattern is for there to be blocking scripts in the head as well as at the end of the document with imagers in between (with some of the images in the viewport).

Technically both the scripts at the beginning and the end are both blocking but the visible images may be of a higher importance to deliver than the scripts at the end.  If we recommend that all of the blocking resources be delivered before non-blocking it would invert those (granted it is only a SHOULD but implementing to the spec might lead to worse performance in that case).

**Comment by kazuho** [comment] 2019-07-03 22:40
Thank you for spotting the issue!

I think we have two options.

The first is to replace "processing" with "using". I think the problem is in discussing if "processing" of the document is blocked. If we change that to a discussion of if the "use" of the document is blocked, then I think the text would naturally imply that scripts in body should not be given `urgency=blocking`.

The other option is to choose a different term. One attractive choice is to reuse the terms defined in Priority Hints, but the question is if they would match nicely to the model we need in HTTP prioritization. As we have been discussing in #12, importance=high does not maps (or should not be mapped) to urgency=blocking.

**Comment by kazuho** [comment] 2019-07-04 01:45
Replying to myself:
> The first is to replace "processing" with "using".

#14 does that. I think it would be a better approach than changing the terms to "high" / "low", if we are to add things like "deferred" (to indicate that a resource is a script with async attribute).

**Comment by kazuho** [comment] 2019-07-04 13:24
@pmeenan #14 has been merged. Please close the issue if you are happy with it, otherwise let's discuss other options.

**Closed as completed** 2020-02-27 15:45 UTC
Labels: pending-closure

**Comment by LPardue** [comment] 2020-02-27 15:50
We merged a change to the issue at the time, and subsequent changes to the draft
have rendered this stale. Closing the issue but feel free to open a new one
against the current document.
